name: CI

on: push

jobs:
  run:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer install
      - run: git config --global user.email "scrutinizer-ci@github.com"
      - run: git config --global user.name "Scrutinizer-CI"
      - run: php vendor/bin/phpunit
